
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/apple/Desktop/CODE/build/assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("428x926")
window.configure(bg = "#121212")


canvas = Canvas(
    window,
    bg = "#121212",
    height = 926,
    width = 428,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    80.0,
    40.0,
    anchor="nw",
    text="Choose 3 or more artists you like.",
    fill="#FFFFFF",
    font=("AvenirNext Bold", 16 * -1)
)

canvas.create_text(
    61.0,
    100.0,
    anchor="nw",
    text="Search",
    fill="#000000",
    font=("AvenirNext Medium", 14 * -1)
)

canvas.create_text(
    189.0,
    242.0,
    anchor="nw",
    text="Next",
    fill="#000000",
    font=("AvenirNext DemiBold", 15 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    214.0,
    538.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    211.0,
    108.0,
    image=image_image_2
)

canvas.create_text(
    59.0,
    100.0,
    anchor="nw",
    text="Search",
    fill="#000000",
    font=("AvenirNext Medium", 14 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    43.0,
    109.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
