
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/apple/Desktop/CODE/build/assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("428x926")
window.configure(bg = "#121212")


canvas = Canvas(
    window,
    bg = "#121212",
    height = 926,
    width = 428,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    215.0,
    173.0,
    image=image_image_1
)

canvas.create_text(
    63.0,
    165.0,
    anchor="nw",
    text="Search",
    fill="#000000",
    font=("AvenirNext Medium", 14 * -1)
)

canvas.create_text(
    27.0,
    81.0,
    anchor="nw",
    text="Now choose some podcasts.",
    fill="#FFFFFF",
    font=("Arial BoldMT", 26 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    213.0,
    584.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    47.0,
    174.0,
    image=image_image_3
)
window.resizable(False, False)
window.mainloop()
